name: flutter_bluetooth_printer
description: Image based printing for bluetooth thermal printer, support for iOS and Android.
version: 2.8.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  image: ">=4.1.3"
  esc_pos_utils_plus: ">=2.0.3"
  flutter_bluetooth_printer_platform_interface:
    path: ../flutter_bluetooth_printer_platform_interface
  plugin_platform_interface: ^2.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        package: id.flutter.plugins
        pluginClass: FlutterBluetoothPrinterPlugin
        dartPluginClass: FlutterBluetoothPrinter
      ios:
        pluginClass: FlutterBluetoothPrinterPlugin
        dartPluginClass: FlutterBluetoothPrinter

  fonts:
    - family: HermeneusOne
      fonts:
        - asset: fonts/HermeneusOne-Regular.ttf
